### ISSUE TITLE
xml2js does not preserve element order within a level

### ISSUE THREAD

**Issue by DaBlick** [Leonidas-from-XIV/node-xml2js#31]
Here's the input XML

	<nj:entitySection>
		<nj:entity entityName="Student">
			<nj:subEntity subEntityName="Contact" >
				<nj:fieldGroup displayName="group1">
					<nj:inModelField displayName="field1"  />
					<nj:foobar>x</nj:foobar>
					<nj:inModelField  displayName="field2"  />
				</nj:fieldGroup>
				<nj:fieldGroup displayName="group2">
					<nj:inModelField displayName="field3"/>
				</nj:fieldGroup>
			</nj:subEntity>
		</nj:entity>
	</nj:entitySection>
    </nj:ReportingStandard>

And here's what xml2js reads in:

    { 'nj:entitySection': 
      [ { 'nj:entity': 
           [ { '@': { entityName: 'Student' },
               'nj:subEntity': 
                [ { 'nj:fieldGroup': 
                     [ { 'nj:foobar': [ 'x', [length]: 1 ],
                         '@': { displayName: 'group1' },
                         'nj:inModelField': [ [Object], [Object], [length]: 2 ] },
                       { '@': { displayName: 'group2' },
                         'nj:inModelField': [ [Object], [length]: 1 ] },
                       [length]: 2 ],
                    '@': { subEntityName: 'Contact' } },
                  [length]: 1 ] },
             [length]: 1 ] },
        [length]: 1 ],

The key thing to notice is that in the xml its:
Originally the order was:

 * inModelField
 * foo
 * inModelField

but in the result, it's more like:

 * foo
 * inModelField
 * inModelField

it basically combines all tags with the same element name at a particular level, and in so doing, BLOWS away the (XML proscribed) preservation of tag order. And there's no way to re-establish the original order.

So if you tried to represent your XHTML with this, all your p, h, a and such tags would all scrunched with identical tags

    H P P A H A P P H   would become
    A A H H H P P P P   !!!!!

Note: I'm not trying to read in XHTML - i just used those tags as an example of why it might be a problem for some schemas.

xml2js does have this sexy sounding option:

    explicitArray (default: false): Always put child nodes in an array if true;    otherwise an array is created only if there is more than one.

While it does indeed "put child nodes in an array", it doesn't preserve the document order.

**Comment by ryedin** [comment]
Any update on this issue?

This is a very common issue in a lot of XML docs. I would think the solution here could be as simple as changing the object model to add a `_children_` array to all nodes, which populates in order of child node occurrence... and yes, probably as an optional behavior.

**Comment by Leonidas-from-XIV** [comment]
Currently no work is being done, but if you feel like submitting a PR that changes the current behaviour to something more sane (a.k.a preserving the order), I'd definitely be interested.

**Comment by ryedin** [comment]
OK, I'll make a fork and take a look at the code to see if I can come up with something. No promises of course :)

**Comment by ryedin** [comment]
OK, so, the above PR provides us with what I view is a viable workaround for this issue. In this configuration the parser behaves like normal (still collects nodes in named properties for convenience) with the "children" field now becoming and ordered array. The nodes all keep the `#name` field now so the children array can be iterated and node names checked if needed (very common case).

Note: both `explicitChildren` and `preserveChildrenOrder` must be `true`, and it _does_ modify the behavior of `explicitChildren` in a way that will break code that relied on it previously (`$$` is no longer a single object but the actual array of children) -- this breakage is why I made the `preserveChildrenOrder` an explicit option to override the behavior of `explicitChildren` instead of simply changing how `explicitChildren` works.

**Comment by apendua** [comment]
@ryedin @Leonidas-from-XIV Is it already published in the latest release, i.e. `0.4.8`? To me it still looks like the `$$` property is an object rather than an array even though I am using both `explicitChildren` and 'explicitChildren' modifiers. Maybe I am doing something wrong.

**Comment by Leonidas-from-XIV** [comment]
@apendua As the README says, these options are only available starting with `0.4.9` (when it will be released) and git `master`.

**Comment by ryedin** [comment]
@apendua if you need the feature right away, you can change your `package.json` to point to `Leonidas-from-XIV/node-xml2js` which will tell npm to pull directly from the github repo instead of the last published npm package.

**Comment by apendua** [comment]
@ryedin Thanks for response. I was confused because for some reason I thought that your latest PR ended up in `0.4.8` - probably because of the commit date. I can see now that in fact it's the other way around:

https://github.com/Leonidas-from-XIV/node-xml2js/compare/0.4.8...master

This said I also thought `0.4.9` was a typo error in your `README.md` @Leonidas-from-XIV because such a release does not even exists. But anyway, thanks for explanation. A lot of confusion but everything seems to be clear now.

**Comment by Leonidas-from-XIV** [comment]
> This said I also thought 0.4.9 was a typo error in your README.md @Leonidas-from-XIV because such a release does not even exists.

The `master` version will be released as `0.4.9`, so the `README.md` is correct. If it references a version that is in the future, it means that it will be part of a future release.

I released `0.4.8` before merging @ryedin's patch, to make sure there is a recent release in case things will break, so there is a version to quickly roll back to. I suppose since there have't been many complaints, I'll release `0.4.9` soon.

**Comment by boopathi** [comment]
While rebuilding this ordered js to xml, the builder doesn't rebuild it in the ordered form. The order gets messed up again while building it back. Is there any workaround for that ?

**Comment by drasive** [comment]
This is still an issue. At the moment, a one to one bi-directional conversion is guaranteed only for default configuration" (from the README) is therefore not correct.

**Comment by Leonidas-from-XIV** [comment]
Yes, I should remove the note about that for now until I have time to rewrite it.

**Comment by bluenote10** [comment]
It is also weird that it is still the default behavior to mess up the order. That is not what one expects an XML parser does, because in XML order matters. A bit of an annoying gotcha to default to something that doesn't make sense with XML.
